# 我这个docker-compose由几个服务组成
services:
  mysql8:
    #    镜像版本
    image: mysql:8.0
    #    重启策略
    restart: always4
    #    密码登录
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'cyf2001323'
    volumes:
      #      脚本文件
      - ./script/mysql/:/docker-entrypoint-initdb.d
    ports:
      #      外部访问13316
      - 13316:3306
